### ISSUE TITLE
README.mk and license notice

### ISSUE THREAD

**Issue by dobryj** [joembedded/JesFs#2]
Hi,
I don't know how to tell you "thanks" for the change of license to more tolerant LGPL.
Can you change notice about license in README.md too?

Thanks!!!

PS: it looks promising

**Comment by FreddieChopin** [comment]
As far as I know, LGPL for a "deeply embedded" applications (like microcontrollers) is no different than GPL. LGPL has basically just one advantage over GPL - it allows proprietary code to be DYNAMICALLY linked to LGPL library. In microcontrollers everything is linked statically, so there is basically no difference between GPL and LGPL - using LGPL library forces you to release everything as LGPL (if you sell or share the compiled program). That's why MCU libraries which choose LGPL usually add a so-called "linking exception". JesFs doesn't have that linking exception and without it the "audience" is basically limited to hobby projects only, which is unfortunate, as there are almost no file-systems designed specifically for MCUs, and those that exist are either not-fail-safe (FAT) or have many other problems, which make them non-usable in real-world (littlefs and its performance issues with many files or lots of data).

**Comment by joembedded** [comment]
For a professional system, some encryption (e.g. secure bootloader) would also bee necessary. If you are interested in such projects, drop me a note! Currently I have a new platform, based on NRF52832/NRF52840, SARA-R412(LTE-M/2G) as Sensor/Gateway, including a highly portable Cloud solution.
